/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import dbcon.DB;
import dbcon.StudentDao;
import dbcon.inputFormatting;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Random;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author RavenPC
 */
public class autoAddStudent1 extends javax.swing.JPanel {
  String result;
 String[] parts;

String rfid;
   String studentID ;
   String lastName ;

    /**
     * Creates new form Panel1
     */
    public autoAddStudent1() {
        initComponents();
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        students = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        output = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setBackground(new java.awt.Color(155, 156, 237));
        jLabel1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("  Auto Update RFID");
        jLabel1.setOpaque(true);

        students.setColumns(20);
        students.setRows(5);
        jScrollPane1.setViewportView(students);

        jButton1.setBackground(new java.awt.Color(102, 255, 51));
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        output.setEditable(false);
        output.setColumns(20);
        output.setRows(5);
        jScrollPane2.setViewportView(output);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 721, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
           
String text = students.getText();
String[] inputRows = text.split("\n");
ArrayList<String> rows = new ArrayList<String>();

for (String row : inputRows) {
    // Remove extra spaces using regular expression
    row = row.trim().replaceAll("\\s+", " ");
    rows.add(row);
}

for (String row : rows) {
    System.out.println(row + "\n");
    String result = row;
    String[] parts = result.split(" ");

    String rfid = null;
    String studentID = null;

    for (int i = 3; i < parts.length; i++) {
        if (parts[i].startsWith("00")) {
            rfid = parts[i]; // Assign RFID to the part that starts with "00"
            break; // Exit the loop after finding a valid RFID
        }
    }

    if (rfid != null) {
        // Extract the student ID from the part before RFID and clear non-digit characters
        String studentIDPart = parts[parts.length - 2]; // Second-to-last part
        studentIDPart = studentIDPart.replaceAll("[^0-9]", ""); // Remove non-digit characters

        if (studentIDPart.length() == 9) {
            // Format: **-****-***
            studentID = studentIDPart.substring(0, 2) + "-" + studentIDPart.substring(2, 6) + "-" + studentIDPart.substring(6);
        } else {
            // Format: **- and the rest of the number
            studentID = studentIDPart.substring(0, 2) + "-" + studentIDPart.substring(2);
        }

        int rowsAffected = StudentDao.updateRFID(studentID, rfid);

        if (rowsAffected > 0) {
            output.append(studentID + " " + rfid + " is changed successfully \n");
        } else {

            String studentIDPart1 = parts[parts.length - 3]; // Second-to-last part
            studentIDPart1 = studentIDPart1.replaceAll("[^0-9]", ""); // Remove non-digit characters

            if (studentIDPart1.length() == 9) {
                // Format: **-****-***
                studentID = studentIDPart1.substring(0, 2) + "-" + studentIDPart1.substring(2, 6) + "-" + studentIDPart1.substring(6);
            } else {
                // Format: **- and the rest of the number
//                studentID = studentIDPart1.substring(0, 2) + "-" + studentIDPart1.substring(2);
            }

            int rowsAffected1 = StudentDao.updateRFID(studentID, rfid);
            if (rowsAffected1 > 0) {
                output.append(studentID + " " + rfid + " is changed successfully \n");
            } else {
                output.append(studentID + " " + rfid + " student ID cannot be found in the database \n");
            }
        }
    }
}


    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea output;
    private javax.swing.JTextArea students;
    // End of variables declaration//GEN-END:variables
}
