/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import dbcon.DB;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author RavenPC
 */
public class Fines extends javax.swing.JPanel {
      double totalFines = 0.0,studentChange=0.0; // Initialize a variable to keep track of the total fines

    /**
     * Creates new form Panel1
     */String username;
    public Fines(String username) {
        initComponents();
        this.username=username;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultTable = new javax.swing.JTable();
        change = new javax.swing.JLabel();
        fines = new javax.swing.JLabel();
        payment = new javax.swing.JLabel();
        finesTextField = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setBackground(new java.awt.Color(155, 156, 237));
        jLabel1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel1.setText("  Fines");
        jLabel1.setOpaque(true);

        jButton1.setBackground(new java.awt.Color(51, 204, 255));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        resultTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "RFID", "Student Name", "Event Code", "EventName", "EventDate","Fines"
            }
        ));
        jScrollPane1.setViewportView(resultTable);

        change.setFont(new java.awt.Font("Dubai", 1, 36)); // NOI18N
        change.setForeground(new java.awt.Color(255, 255, 255));
        change.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        change.setText("Change:");

        fines.setFont(new java.awt.Font("Dubai", 1, 36)); // NOI18N
        fines.setForeground(new java.awt.Color(255, 255, 255));
        fines.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        fines.setText("Total Fines:");

        payment.setFont(new java.awt.Font("Dubai", 1, 36)); // NOI18N
        payment.setForeground(new java.awt.Color(255, 255, 255));
        payment.setText("Payment:");

        finesTextField.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        finesTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finesTextFieldActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(102, 153, 255));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Pay");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(336, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(change, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fines, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(payment)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(finesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(64, 64, 64))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(fines, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(payment, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(finesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(change, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// Step 1: Retrieve the RFID from a JTextField
String studRFID = jTextField1.getText();

try {
    Connection conn = DB.getConnection(); // Assuming you have a method to get a database connection
    String query = "SELECT s.rfid, s.firstName, s.middleName, s.lastName, s.extension, e.eventCode, e.eventName, e.eventDate, f.fines " +
                   "FROM fines AS f " +
                   "LEFT JOIN students AS s ON f.studRFID = s.rfid " +
                   "LEFT JOIN events AS e ON f.eventCode = e.eventCode " +
                   "WHERE f.studRFID = ?";
    PreparedStatement preparedStatement = conn.prepareStatement(query);
    preparedStatement.setString(1, studRFID);

    ResultSet resultSet = preparedStatement.executeQuery();

    DefaultTableModel tableModel = new DefaultTableModel();
    tableModel.addColumn("Student RFID"); // Add Student ID column
    tableModel.addColumn("Student Name");
    tableModel.addColumn("Event Code");
    tableModel.addColumn("Event Name");
    tableModel.addColumn("Event Date");
    tableModel.addColumn("Fines");

  
    while (resultSet.next()) {
        String studentID = resultSet.getString("rfid"); // Retrieve student ID
        String firstName = resultSet.getString("firstName");
        String middleName = resultSet.getString("middleName");
        String lastName = resultSet.getString("lastName");
        String extension = resultSet.getString("extension");
        String eventCode = resultSet.getString("eventCode");
        String eventName = resultSet.getString("eventName");
        String eventDate = resultSet.getString("eventDate");
        String fullName = firstName + " " + middleName + " " + lastName + " " + extension;
        String fines = resultSet.getString("fines");

        // Add fines to the total
        totalFines += Double.parseDouble(fines);

        tableModel.addRow(new Object[]{studentID, fullName, eventCode, eventName, eventDate, fines});
    }

    // Add a row for the total fines
    tableModel.addRow(new Object[]{"Total Fines:", "", "", "", "", String.valueOf(totalFines)});

    resultTable.setModel(tableModel);

    if (tableModel.getRowCount() == 0) {
        JOptionPane.showMessageDialog(this, "No results found");
    }
    fines.setText("Total Fines: P " + String.format("%.2f", totalFines));
    resultSet.close();
    preparedStatement.close();
    conn.close();
} catch (SQLException e) {
    e.printStackTrace();
}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 // Step 1: Retrieve the payment amount from a JTextField
     String paymentText = finesTextField.getText();

    // Check if the paymentText is empty or not a valid number
    if (paymentText.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter a valid payment amount.");
        return;
    }

  try {
    double paymentAmount = Double.parseDouble(paymentText);

    // Step 2: Validate that the payment is greater than or equal to total fines
    if (paymentAmount < totalFines) {
        JOptionPane.showMessageDialog(this, "Payment amount must be greater than or equal to total fines.");
        return;
    }
    if (totalFines == 0) {
        JOptionPane.showMessageDialog(this, "Payment Cannot be Processed");
        return;
    }

    // Step 3: Subtract the payment amount from the total fines
    studentChange = paymentAmount - totalFines;

    // Insert payment information into the resultTable for each row
    DefaultTableModel tableModel = (DefaultTableModel) resultTable.getModel();
    int rowCount = tableModel.getRowCount();

    Connection conn = DB.getConnection(); // Assuming you have a method to get a database connection
    String insertQuery = "INSERT INTO payment (rfid, eventCode, payment, receivedDate, receivedBy) VALUES (?, ?, ?,CURDATE(),?)";
    PreparedStatement insertStatement = conn.prepareStatement(insertQuery);

    for (int row = 0; row < rowCount; row++) {
        String rfid = (String) tableModel.getValueAt(row, 0); // Adjust the column index as needed
        String eventCode = (String) tableModel.getValueAt(row, 2); // Adjust the column index as needed
        String paid=(String) tableModel.getValueAt(row,5);

        insertStatement.setString(1, rfid);
        insertStatement.setString(2, eventCode);
        insertStatement.setString(3,paid);
        insertStatement.setString(4, username);

        int rowsAffected = insertStatement.executeUpdate();

        if (rowsAffected == 1) {
            // Handle successful insertion for this row (if needed)
         
            JOptionPane.showMessageDialog(this,"Payment Succesfully Accepted");
             change.setText("Change: P " + String.format("%.2f", studentChange));
        } else {
            // Handle failed insertion for this row (if needed)
            
        }
    }

    // Close resources
    insertStatement.close();
    conn.close();

    // Update the "change" text field
   

} catch (NumberFormatException e) {
    JOptionPane.showMessageDialog(this, "Invalid payment amount. Please enter a valid number.");
} catch (SQLException ex) {
    ex.printStackTrace();
}


    }//GEN-LAST:event_jButton2ActionPerformed

    private void finesTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finesTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_finesTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel change;
    private javax.swing.JLabel fines;
    private javax.swing.JTextField finesTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel payment;
    private javax.swing.JTable resultTable;
    // End of variables declaration//GEN-END:variables
}
