/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import form.Attendance;
import form.Collection;
import form.Student;
import form.Fines;
import form.Events;
import form.Expenses;
import form.Inventory;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import menu.MenuItem;

/**
 *
 * @author RavenPC
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     * @param name
     */
    String username;
    public Main(String name) {
        initComponents();
        jLabel3.setText(name);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        username=name;
        execute();
    }
    JpanelLoader jpload = new JpanelLoader();
    private void execute() {
        ImageIcon iconStudent = new ImageIcon(getClass().getResource("/icons/student.png"));
        ImageIcon iconEvents = new ImageIcon(getClass().getResource("/icons/calendar.png"));
        ImageIcon iconAttendance = new ImageIcon(getClass().getResource("/icons/attendance.png"));
        ImageIcon iconInventory=  new ImageIcon(getClass().getResource("/icons/inventory.png"));
        ImageIcon iconSubMenu = new ImageIcon(getClass().getResource("/icons/subMenu.png"));
       //  create submenu staff
        MenuItem menuTreasurer1 = new MenuItem(iconSubMenu, "Fines", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                 Fines cus = new Fines();
        jpload.jPanelLoader(panelBody, cus);
            }
        });
           MenuItem menuTreasurer2 = new MenuItem(iconSubMenu, "Collection", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                 Collection cus = new Collection();
        jpload.jPanelLoader(panelBody, cus);
            }
        });
        MenuItem menuTreasurer3 = new MenuItem(iconSubMenu, "Expenses", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                 Expenses cus = new Expenses();
        jpload.jPanelLoader(panelBody, cus);
            }
        });
        // Set subMenu Colors
         Color subMenuColor = new Color(0, 204, 250); 
        Color subMenuFontColor= new Color(0,0,0);
        
          MenuItem menuStudent = new MenuItem(iconStudent, "Students", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                 Student cus = new Student(username);
        jpload.jPanelLoader(panelBody, cus);
            }
        });
       // menuStaff.setSubMenuColor(subMenuColor,subMenuFontColor);
          MenuItem menuEvents = new MenuItem(iconEvents, "Events", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                 Events cus = new Events();
        jpload.jPanelLoader(panelBody, cus);
            }
        });
          
             MenuItem menuAttendance = new MenuItem(iconAttendance, "Attendance", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                 Attendance cus = new Attendance();
        jpload.jPanelLoader(panelBody, cus);
            }
        });
//        menuSetting.setSubMenuColor(subMenuColor,subMenuFontColor);
          
             MenuItem menuInventory = new MenuItem(iconInventory, "Inventory", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                Inventory cus = new Inventory();
        jpload.jPanelLoader(panelBody, cus);
            }
        });
        MenuItem menuTreasurer = new MenuItem(iconStudent, "Treasury", null, menuTreasurer1, menuTreasurer2,menuTreasurer3);
         menuTreasurer.setSubMenuColor(subMenuColor,subMenuFontColor);
        addMenu(menuStudent, menuEvents,menuAttendance, menuInventory,menuTreasurer);
       
  
   
    }

    private void addMenu(MenuItem... menu) {
        for (int i = 0; i < menu.length; i++) {
            menus.add(menu[i]);
            ArrayList<MenuItem> subMenu = menu[i].getSubMenu();
            for (MenuItem m : subMenu) {
                addMenu(m);
            }
        }
        menus.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelHeader = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        panelMenu = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        menus = new javax.swing.JPanel();
        panelBody = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("COMPESA Automated Event Handler");

        panelHeader.setBackground(new java.awt.Color(0, 0, 153));
        panelHeader.setPreferredSize(new java.awt.Dimension(561, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-events-50.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("UBCOMPESA EVENT HANDLER SYSTEM");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("jLabel3");

        javax.swing.GroupLayout panelHeaderLayout = new javax.swing.GroupLayout(panelHeader);
        panelHeader.setLayout(panelHeaderLayout);
        panelHeaderLayout.setHorizontalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHeaderLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelHeaderLayout.setVerticalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHeaderLayout.createSequentialGroup()
                .addGroup(panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addGroup(panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelHeaderLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel1))
                        .addGroup(panelHeaderLayout.createSequentialGroup()
                            .addGap(15, 15, 15)
                            .addComponent(jLabel2))))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        getContentPane().add(panelHeader, java.awt.BorderLayout.PAGE_START);

        panelMenu.setBackground(new java.awt.Color(115, 120, 230));
        panelMenu.setPreferredSize(new java.awt.Dimension(250, 384));

        jScrollPane1.setBorder(null);

        menus.setBackground(new java.awt.Color(0, 0, 255));
        menus.setLayout(new javax.swing.BoxLayout(menus, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(menus);

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
        );

        getContentPane().add(panelMenu, java.awt.BorderLayout.LINE_START);

        panelBody.setBackground(new java.awt.Color(255, 255, 255));
        panelBody.setLayout(new java.awt.BorderLayout());
        getContentPane().add(panelBody, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(871, 473));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main("user").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel menus;
    private javax.swing.JPanel panelBody;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JPanel panelMenu;
    // End of variables declaration//GEN-END:variables
}
